[package]
name = "cy-core"
description = "穿云客户端核心库：连接管理、隧道引擎、重连、本地 API"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cy-proto = { workspace = true, features = ["codec", "mux"] }

tokio.workspace = true
tokio-util = { workspace = true, features = ["rt", "codec", "compat"] }
futures.workspace = true

tokio-rustls.workspace = true
rustls.workspace = true
rustls-pki-types.workspace = true
yamux.workspace = true

axum.workspace = true
hyper.workspace = true
hyper-util.workspace = true

serde.workspace = true
serde_json.workspace = true
toml.workspace = true

anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
directories.workspace = true
reqwest.workspace = true
sha2.workspace = true
hex.workspace = true
webpki-roots = "1.0.9"
base64 = "0.23.1"

[dev-dependencies]
axum.workspace = true
rcgen.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tower = "0.5.3"
tracing-subscriber.workspace = true
